const employees = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "leanne@example.com",
    phone: "123-456-7890",
    website: "leanne.com",
    department: "IT",
    position: "Senior Developer",
    status: "Active",
    salary: 50000,
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "ervin@example.com",
    phone: "234-567-8901",
    website: "ervin.com",
    department: "HR",
    position: "HR Manager",
    status: "Active",
    salary: 45000,
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "clementine@example.com",
    phone: "345-678-9012",
    website: "clementine.com",
    department: "Finance",
    position: "Financial Analyst",
    status: "Active",
    salary: 55000,
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "patricia@example.com",
    phone: "456-789-0123",
    website: "patricia.com",
    department: "Marketing",
    position: "Marketing Lead",
    status: "Active",
    salary: 48000,
  },
];

module.exports = employees;